### ISSUE TITLE
AttributeError: 'SearchQuerySet' object has no attribute 'model'

### ISSUE THREAD

**Issue by cdrandin** [inonit/drf-haystack#115]
So, actually, I found the problem now.

Any classes that inherit `HaystackViewSet` requires `permission_classes`. I added it and it worked, it seemed to never use the default one `DEFAULT_PERMISSION_CLASSES` set in haystack in the settings file. Even doing `permission_classes = ()` corrects the issue.

traceback:

```
Traceback (most recent call last):
  File ".../env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File ".../env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".../env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File ".../env/lib/python2.7/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File ".../env/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File ".../env/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File ".../env/lib/python2.7/site-packages/rest_framework/views.py", line 477, in dispatch
    self.initial(request, *args, **kwargs)
  File ".../env/lib/python2.7/site-packages/rest_framework/views.py", line 395, in initial
    self.check_permissions(request)
  File ".../env/lib/python2.7/site-packages/rest_framework/views.py", line 328, in check_permissions
    if not permission.has_permission(request, self):
  File ".../env/lib/python2.7/site-packages/rest_framework/permissions.py", line 142, in has_permission
    perms = self.get_required_permissions(request.method, queryset.model)
AttributeError: 'SearchQuerySet' object has no attribute 'model'
```

**Comment by rhblind** [comment]
Thanks for the report, I'll have a look at it.

**Comment by rhblind** [comment]
Hi, sorry for nothing happening here. Do you still have issues with this? Can you try using the latest v1.8.1?
I'm not able to reproduce this in the test suite.

**Comment by rhblind** [comment]
Hey, I'll close this for now due to no response.
Please reopen if issue persists.

**Comment by trepmag** [comment]
Hello rhblind, could reproduce this issue using the 1.8.4!

Indeed, it works by using `permission_classes = []` or `permission_classes = [IsAuthenticated]` as mentioned in doc at https://drf-haystack.readthedocs.io/en/latest/08_permissions.html#permissions-label. But it says also there that setting 'permission_classes' is to override a the default rest_framework.permissions.AllowAny permission class!

Perhaps a regression over the release v1.5.0 (https://drf-haystack.readthedocs.io/en/latest/#v1-5-0)?...

**Comment by rhblind** [comment]
Huh, yeah seems like it. Thanks, I'll try to make a fix soonish!

**Comment by rhblind** [comment]
It seems to me like this is only happening when trying to apply `DjangoObjectPermissions` or any permission class inherited by that. These classes are [not supported](https://drf-haystack.readthedocs.io/en/latest/08_permissions.html#permissions-label) since the `SearchQuerySet` does not have a single `model` attribute.

Can you guys please confirm if this is the issue?

**Comment by trepmag** [comment]
Can confirm that using `permission_classes = [DjangoObjectPermissions]` trigger the issue!

**Comment by rhblind** [comment]
@trepmag Thanks. That is not supported at the moment, but maybe I'll add some kind of support for it down the road if this is a desired feature.
